#!/bin/bash
# Regenerates shim/scaler_spv.h (committed) from the GLSL in shim/scaler/:
# SPIR-V for Vulkan 1.0 as C arrays. Needs glslangValidator (brew install
# glslang); the build itself does not.
set -euo pipefail
cd "$(dirname "$0")/../.."
tmp=$(mktemp -d)
trap 'rm -rf "$tmp"' EXIT
out=shim/scaler_spv.h
{
    echo "// GENERATED by shim/scaler/build_spv.sh from shim/scaler/*.{vert,frag} -- do not edit."
    echo "// easu/rcas include AMD FidelityFX Super Resolution 1.0 (third_party/fsr1, MIT)."
    echo "#include <stdint.h>"
    for s in fullscreen.vert easu.frag rcas.frag; do
        n=${s%%.*}
        glslangValidator -V --target-env vulkan1.0 -Ithird_party/fsr1 -o "$tmp/$n.spv" "shim/scaler/$s" >/dev/null
        python3 - "$tmp/$n.spv" "$n" <<'PY'
import struct, sys
data = open(sys.argv[1], "rb").read()
words = struct.unpack("<%dI" % (len(data) // 4), data)
print("static const uint32_t spv_%s[%d] = {" % (sys.argv[2], len(words)))
for i in range(0, len(words), 8):
    print("    " + ", ".join("0x%08x" % w for w in words[i:i + 8]) + ",")
print("};")
PY
    done
} > "$out.new"
mv -f "$out.new" "$out"
echo "wrote $out"
