#!/usr/bin/env python3
"""Write JitChurn.java: many small hot methods, for a JIT code cache that
fills, is collected and reuses its memory (tests/android/run.sh,
benchmarks/stage25-art-x86-fex.txt).

Each method mixes its argument with its own constant, so every compiled body
is different code. Run with a small code cache (dalvikvm -Xjitmaxsize:...),
ART compiles, frees and recompiles them at reused addresses; under FEX that
is x86 code rewritten through the cache's writable view while its executable
view holds translations of the old code. A stale translation runs the old
method's code and the checksum differs from the Mac's JVM.

  tests/android/gen_jitchurn.py <out-dir> [methods]
"""
import os
import sys

out = sys.argv[1]
n = int(sys.argv[2]) if len(sys.argv) > 2 else 400
lines = [
    "// Generated by tests/android/gen_jitchurn.py; see there.",
    "public class JitChurn {",
]
for k in range(n):
    c = (0x9E3779B97F4A7C15 * (k + 1)) & 0x7FFFFFFFFFFFFFFF
    lines += [
        f"    static long m{k}(long x) {{",
        f"        long a = x ^ {c}L;",
        "        for (int i = 0; i < 48; i++) {",
        f"            a = a * 6364136223846793005L + {k * 2 + 1}L;",
        f"            a ^= a >>> {(k % 23) + 7};",
        "        }",
        "        return a;",
        "    }",
    ]
lines += [
    "    static long call(int k, long x) {",
    "        switch (k) {",
]
lines += [f"            case {k}: return m{k}(x);" for k in range(n)]
lines += [
    "            default: return 0;",
    "        }",
    "    }",
    "    public static void main(String[] args) {",
    "        int rounds = args.length > 0 ? Integer.parseInt(args[0]) : 6;",
    "        int calls = args.length > 1 ? Integer.parseInt(args[1]) : 300;",
    f"        int n = {n};",
    "        long total = 0;",
    "        for (int r = 0; r < rounds; r++) {",
    "            long sum = 0;",
    "            // A different order each round, so methods are compiled,",
    "            // collected and compiled again in a different place.",
    "            for (int j = 0; j < n; j++) {",
    "                int k = (int) ((j * 7L + r * 13L) % n);",
    "                for (int c = 0; c < calls; c++) sum += call(k, c + r);",
    "            }",
    "            System.out.println(\"round \" + r + \" sum=\" + sum);",
    "            total ^= sum * (r + 1);",
    "        }",
    "        System.out.println(\"total=\" + total);",
    "    }",
    "}",
]
os.makedirs(out, exist_ok=True)
with open(os.path.join(out, "JitChurn.java"), "w") as f:
    f.write("\n".join(lines) + "\n")
