#!/usr/bin/env python3
"""Generate the ELF libvulkan.so.1 shim from a list of entry points.

DXVK and every other Vulkan consumer link against libvulkan.so.1 by SONAME and
call its entry points directly; they will never call the runtime's private
bridge syscalls themselves. This generates an ordinary Linux shared object whose
entry points tail-call into Mach-O MoltenVK.

A tail call is signature-agnostic: arguments stay in the registers and on the
stack exactly where the caller put them, so one four-instruction thunk works for
every prototype without knowing any of them.
"""

import sys

names = [l.strip() for l in open(sys.argv[1]) if l.strip()]
asm_path, c_path = sys.argv[2], sys.argv[3]
# Entry points shim/wsi.c implements itself: their tail-call thunk is emitted
# as the hidden symbol lxrt_mvk_<name> (MoltenVK's version, for wsi.c to call)
# and the exported <name> comes from wsi.c.
overrides = set()
if len(sys.argv) > 4:
    overrides = {l.strip() for l in open(sys.argv[4]) if l.strip() and not l.startswith("#")}

with open(asm_path, "w") as f:
    f.write("""// GENERATED by shim/gen.py -- do not edit.
//
// One tail-call thunk per Vulkan entry point. x16 (IP0) is the register AAPCS64
// reserves for exactly this kind of veneer, so clobbering it is correct rather
// than merely convenient.

    .text
""")
    for i, n in enumerate(names):
        sym = f"lxrt_mvk_{n}" if n in overrides else n
        vis = f"\n    .hidden {sym}" if n in overrides else ""
        f.write(f"""
    .globl  {sym}{vis}
    .type   {sym},%function
{sym}:
    adrp    x16, lxrt_vk_table
    add     x16, x16, :lo12:lxrt_vk_table
    ldr     x16, [x16, #{i * 8}]
    cbz     x16, .Lmissing
    br      x16
    .size   {sym}, .-{sym}
""")
    f.write("""
// MoltenVK did not export this entry point. Failing loudly beats branching
// through zero, and the runtime's fault reporter names the address.
.Lmissing:
    brk     #2
""")

with open(c_path, "w") as f:
    f.write("""// GENERATED by shim/gen.py -- do not edit.
//
// Resolves every entry point once, at load time, through the runtime's host
// bridge. No libc: the shim is built -nostdlib so it drags nothing in.

#include "lxrt_host.h"

__attribute__((visibility("hidden")))
void *lxrt_vk_table[%d];

static const char *const k_names[] = {
""" % len(names))
    for n in names:
        f.write(f'    "{n}",\n')
    f.write("""};

// Homebrew first, then the Vulkan SDK. Whichever is present wins; a build that
// finds neither leaves the table null and every entry point traps at brk #2
// rather than silently doing nothing.
static const char *const k_paths[] = {
    "/opt/homebrew/lib/libMoltenVK.dylib",
    "/usr/local/lib/libMoltenVK.dylib",
};

__attribute__((constructor))
static void lxrt_vk_init(void)
{
    void *h = 0;
    for (unsigned i = 0; i < sizeof(k_paths) / sizeof(k_paths[0]) && !h; i++)
        h = lxrt_host_dlopen(k_paths[i], 0);
    if (!h)
        return;
    for (unsigned i = 0; i < sizeof(k_names) / sizeof(k_names[0]); i++)
        lxrt_vk_table[i] = lxrt_host_dlsym(h, k_names[i]);
}
""")
print(f"{len(names)} entry points -> {asm_path}, {c_path}")
