#!/usr/bin/env python3
"""Generate the ELF libvulkan.so.1 shim from a list of entry points.

DXVK and every other Vulkan consumer link against libvulkan.so.1 by SONAME and
call its entry points directly; they will never call the runtime's private
bridge syscalls themselves. This generates an ordinary Linux shared object whose
entry points tail-call into Mach-O MoltenVK.

A tail call is signature-agnostic: arguments stay in the registers and on the
stack exactly where the caller put them, so one four-instruction thunk works for
every prototype without knowing any of them.
"""

import sys

names = [l.strip() for l in open(sys.argv[1]) if l.strip()]
asm_path, c_path = sys.argv[2], sys.argv[3]
# Entry points shim/wsi.c implements itself: their tail-call thunk is emitted
# as the hidden symbol lxrt_mvk_<name> (MoltenVK's version, for wsi.c to call)
# and the exported <name> comes from wsi.c.
overrides = set()
if len(sys.argv) > 4:
    overrides = {l.strip() for l in open(sys.argv[4]) if l.strip() and not l.startswith("#")}

with open(asm_path, "w") as f:
    f.write("""// GENERATED by shim/gen.py -- do not edit.
//
// One tail-call thunk per Vulkan entry point. x16 (IP0) is the register AAPCS64
// reserves for exactly this kind of veneer, so clobbering it is correct rather
// than merely convenient.

    .text
""")
    for i, n in enumerate(names):
        sym = f"lxrt_mvk_{n}" if n in overrides else n
        vis = f"\n    .hidden {sym}" if n in overrides else ""
        f.write(f"""
    .globl  {sym}{vis}
    .type   {sym},%function
{sym}:
    adrp    x16, lxrt_vk_table
    add     x16, x16, :lo12:lxrt_vk_table
    ldr     x16, [x16, #{i * 8}]
    cbz     x16, .Lmissing
    br      x16
    .size   {sym}, .-{sym}
""")
    f.write("""
// MoltenVK did not export this entry point. Failing loudly beats branching
// through zero, and the runtime's fault reporter names the address.
.Lmissing:
    brk     #2

// LXRT_VK_CALLS=1: one counting thunk per entry point. The table then holds
// these, and the driver's own pointers are in lxrt_vk_real. The increment is
// not atomic: a diagnostic's count may lose a call between threads. x17 (IP1)
// is the other register a veneer may use.
""")
    for i, n in enumerate(names):
        f.write(f"""
.Lcnt{i}:
    adrp    x17, lxrt_vk_counts
    add     x17, x17, :lo12:lxrt_vk_counts
    ldr     x16, [x17, #{i * 8}]
    add     x16, x16, #1
    str     x16, [x17, #{i * 8}]
    adrp    x16, lxrt_vk_real
    add     x16, x16, :lo12:lxrt_vk_real
    ldr     x16, [x16, #{i * 8}]
    br      x16
""")
    f.write("""
    .section .data.rel.ro,"aw"
    .p2align 3
    .globl  lxrt_vk_cnt_thunks
    .hidden lxrt_vk_cnt_thunks
lxrt_vk_cnt_thunks:
""")
    for i, n in enumerate(names):
        f.write(f"    .quad   .Lcnt{i}\n")

with open(c_path, "w") as f:
    f.write("""// GENERATED by shim/gen.py -- do not edit.
//
// Resolves every entry point once, at load time, through the runtime's host
// bridge. No libc: the shim is built -nostdlib so it drags nothing in.

#include "lxrt_host.h"

__attribute__((visibility("hidden")))
void *lxrt_vk_table[%d];

// LXRT_VK_CALLS=1 (vulkan_shim.S): the driver's entry points while the table
// holds the counting thunks, and how often each was called.
__attribute__((visibility("hidden"))) void *lxrt_vk_real[%d];
__attribute__((visibility("hidden"))) unsigned long long lxrt_vk_counts[%d];
__attribute__((visibility("hidden"))) int lxrt_vk_calls_on;
extern void *const lxrt_vk_cnt_thunks[%d] __attribute__((visibility("hidden")));

static const char *const k_names[] = {
""" % (len(names), len(names), len(names), len(names)))
    for n in names:
        f.write(f'    "{n}",\n')
    f.write("""};
#define N_NAMES (sizeof(k_names) / sizeof(k_names[0]))
""")
    for n in ("vkCreateInstance", "vk_icdGetInstanceProcAddr",
              "vkEnumerateInstanceLayerProperties", "vkEnumerateDeviceLayerProperties"):
        f.write(f"#define I_{n} {names.index(n)}\n")
    f.write("""
// Homebrew first, then the Vulkan SDK. Whichever is present wins; a build that
// finds neither leaves the table null and every entry point traps at brk #2
// rather than silently doing nothing.
static const char *const k_paths[] = {
    "/opt/homebrew/lib/libMoltenVK.dylib",
    "/usr/local/lib/libMoltenVK.dylib",
};

// STEAMARM_VK_ICD picks another driver: "kosmickrisp" (Mesa's Vulkan-on-Metal
// driver: the one in STEAMARM_KK_DIR if that is set and holds one, else
// Homebrew's mesa), or the absolute path of a dylib. Unset or
// "moltenvk": MoltenVK as above. A driver that cannot be used falls back to
// MoltenVK, and says so on stderr.
static const char *const k_kk_paths[] = {
    "/opt/homebrew/lib/libvulkan_kosmickrisp.dylib",
    "/usr/local/lib/libvulkan_kosmickrisp.dylib",
};

// STEAMARM_VK_ICD_FOR=NAME=DRIVER[;NAME=DRIVER...]: the driver for one
// program, over STEAMARM_VK_ICD. NAME is the guest program's file name
// (argv[1] of the runtime, or argv[2] under FEX). The launcher keeps Steam's
// web helper on MoltenVK this way: KosmicKrisp could not compile ANGLE's
// pipelines (vkCreateGraphicsPipelines -> VK_ERROR_INVALID_SHADER_NV, 831
// times in a minute, and a black window; MEASURED, benchmarks/stage49).
static const char *driver_for_program(char *(*henv)(const char *), const char *req)
{
    static char pick[64];
    const char *spec = henv ? henv("STEAMARM_VK_ICD_FOR") : 0;
    char ***(*nsargv)(void) = (char ***(*)(void))lxrt_host_dlsym((void *)-2, "_NSGetArgv");
    int *(*nsargc)(void) = (int *(*)(void))lxrt_host_dlsym((void *)-2, "_NSGetArgc");
    if (!spec || !*spec || !nsargv || !nsargc)
        return req;
    char **argv = *nsargv();
    int argc = *nsargc();
    for (int a = 1; a < argc && a <= 2; a++) {
        const char *base = argv[a];
        for (const char *p = argv[a]; *p; p++)
            if (*p == '/')
                base = p + 1;
        for (const char *e = spec; *e;) {
            const char *eq = e, *end = e;
            while (*eq && *eq != '=' && *eq != ';')
                eq++;
            end = eq;
            while (*end && *end != ';')
                end++;
            if (*eq == '=') {
                unsigned n = (unsigned)(eq - e), i;
                for (i = 0; i < n && base[i] == e[i]; i++)
                    ;
                if (i == n && base[n] == 0 && (unsigned)(end - eq - 1) < sizeof pick) {
                    unsigned k = 0;
                    for (const char *v = eq + 1; v < end; v++)
                        pick[k++] = *v;
                    pick[k] = 0;
                    return pick;
                }
            }
            e = *end ? end + 1 : end;
        }
    }
    return req;
}

// ICD mode: a driver that exports only the loader-ICD interface (Mesa's
// drivers export vk_icd* and nothing else, MEASURED with nm). Its entry points
// are asked of vk_icdGetInstanceProcAddr -- the global ones here, every other
// one once an instance exists (lxrt_vk_icd_fill). Dispatchable handles need
// nothing from the shim: their first word is VK_LOADER_DATA, which both
// MoltenVK and Mesa set to ICD_LOADER_MAGIC and never read (Mesa dispatches
// through vk_object_base->device; MEASURED: the word stays 0x01CDC0DE through
// a whole submit on either driver with no loader).
typedef void *(*lxrt_gipa_fn)(void *instance, const char *name);
__attribute__((visibility("hidden"))) int lxrt_vk_icd;
__attribute__((visibility("hidden"))) const char *lxrt_vk_driver = "none";
static lxrt_gipa_fn g_gipa;
static volatile int g_fill_lock;

static int s_eq(const char *a, const char *b)
{
    while (*a && *a == *b) { a++; b++; }
    return *a == *b;
}

// stderr before the guest's libc may be initialised: Linux write(2) straight
// to the runtime, the parts joined with no formatting.
static void say(const char *const *parts)
{
    char buf[512];
    unsigned n = 0;
    for (; *parts; parts++)
        for (const char *p = *parts; *p && n < sizeof buf - 1; p++)
            buf[n++] = *p;
    buf[n++] = '\\n';
    lxrt_syscall3(64 /* write */, 2, (long)(uintptr_t)buf, n);
}

// The loader implements these; a driver need not.
static int32_t no_instance_layers(uint32_t *count, void *props) { (void)props; *count = 0; return 0; }
static int32_t no_device_layers(void *pd, uint32_t *count, void *props) { (void)pd; (void)props; *count = 0; return 0; }

// Fill the table from `h`. Returns 0 if it holds no usable Vulkan driver.
static int bind(void *h)
{
    lxrt_gipa_fn gipa = (lxrt_gipa_fn)lxrt_host_dlsym(h, "vk_icdGetInstanceProcAddr");
    if (lxrt_host_dlsym(h, "vkCreateInstance") || !gipa) {
        for (unsigned i = 0; i < N_NAMES; i++)
            lxrt_vk_table[i] = lxrt_host_dlsym(h, k_names[i]);
        return lxrt_vk_table[I_vkCreateInstance] != 0;
    }
    int32_t (*neg)(uint32_t *) = (int32_t (*)(uint32_t *))lxrt_host_dlsym(h, "vk_icdNegotiateLoaderICDInterfaceVersion");
    uint32_t version = 7;   // CURRENT_LOADER_ICD_INTERFACE_VERSION (vk_icd.h)
    if (neg && neg(&version) != 0)
        return 0;
    for (unsigned i = 0; i < N_NAMES; i++)
        lxrt_vk_table[i] = gipa(0, k_names[i]);
    if (!lxrt_vk_table[I_vkCreateInstance])
        return 0;
    lxrt_vk_table[I_vk_icdGetInstanceProcAddr] = (void *)gipa;
    if (!lxrt_vk_table[I_vkEnumerateInstanceLayerProperties])
        lxrt_vk_table[I_vkEnumerateInstanceLayerProperties] = (void *)no_instance_layers;
    if (!lxrt_vk_table[I_vkEnumerateDeviceLayerProperties])
        lxrt_vk_table[I_vkEnumerateDeviceLayerProperties] = (void *)no_device_layers;
    g_gipa = gipa;
    lxrt_vk_icd = 1;
    return 1;
}

__attribute__((constructor))
static void lxrt_vk_init(void)
{
    // The host's getenv: the environment the runtime was started (or
    // re-executed, runtime/process.c) with, which is the guest's; readable
    // before the guest's libc is initialised.
    char *(*henv)(const char *) = (char *(*)(const char *))lxrt_host_dlsym((void *)-2 /* RTLD_DEFAULT */, "getenv");
    const char *req = driver_for_program(henv, henv ? henv("STEAMARM_VK_ICD") : 0);
    const char *dbg = henv ? henv("LXRT_VK_DEBUG") : 0;
    const char *why = 0;
    void *h = 0;
    if (req && *req && !s_eq(req, "moltenvk")) {
        if (s_eq(req, "kosmickrisp")) {
            // SteamARM's own build first (scripts/build-kosmickrisp.sh: the
            // driver with patches/kosmickrisp-*.patch), where the launcher
            // says it is; Homebrew's otherwise.
            const char *dir = henv ? henv("STEAMARM_KK_DIR") : 0;
            static char own[512];
            if (dir && *dir == '/') {
                unsigned n = 0;
                for (const char *p = dir; *p && n < sizeof own - 40; p++)
                    own[n++] = *p;
                for (const char *p = "/libvulkan_kosmickrisp.dylib"; *p; p++)
                    own[n++] = *p;
                own[n] = 0;
                h = lxrt_host_dlopen(own, 0);
            }
            for (unsigned i = 0; i < sizeof(k_kk_paths) / sizeof(k_kk_paths[0]) && !h; i++)
                h = lxrt_host_dlopen(k_kk_paths[i], 0);
        }
        else if (req[0] == '/')
            h = lxrt_host_dlopen(req, 0);
        else
            why = "unknown driver name";
        if (!h && !why)
            why = "dlopen failed";
        if (h && !bind(h)) {
            h = 0;
            why = "no usable Vulkan entry points";
        }
        if (h)
            lxrt_vk_driver = req;
    }
    if (!h) {
        for (unsigned i = 0; i < sizeof(k_paths) / sizeof(k_paths[0]) && !h; i++)
            h = lxrt_host_dlopen(k_paths[i], 0);
        if (h) {
            lxrt_vk_driver = "moltenvk";
            bind(h);
        }
    }
    const char *calls = henv ? henv("LXRT_VK_CALLS") : 0;
    if (calls && *calls == '1') {
        lxrt_vk_calls_on = 1;
        for (unsigned i = 0; i < N_NAMES; i++)
            if (lxrt_vk_table[i]) {
                lxrt_vk_real[i] = lxrt_vk_table[i];
                lxrt_vk_table[i] = lxrt_vk_cnt_thunks[i];
            }
    }
    if (why || (dbg && *dbg == '1'))
        say((const char *const[]){ "[shim] vk driver requested=", req && *req ? req : "moltenvk",
                                   " effective=", lxrt_vk_driver, " (", why ? why : lxrt_vk_icd ? "icd" : "exports",
                                   ")", 0 });
}

// ICD mode, after every vkCreateInstance that succeeds (shim/wsi.c): the
// slots still empty are filled from vk_icdGetInstanceProcAddr(instance). A
// slot is written once. Mesa answers only for what the instance enabled (its
// apiVersion and extensions; MEASURED: NULL for vkCmdBeginRendering from a
// 1.0 instance), so a later instance can fill what an earlier one could not;
// the pointers do not depend on the instance (MEASURED: 431 names, two
// instances, no difference).
__attribute__((visibility("hidden")))
void lxrt_vk_icd_fill(void *instance)
{
    if (!lxrt_vk_icd || !instance)
        return;
    while (__atomic_exchange_n(&g_fill_lock, 1, __ATOMIC_ACQUIRE))
        ;
    for (unsigned i = 0; i < N_NAMES; i++)
        if (!lxrt_vk_table[i]) {
            void *f = g_gipa(instance, k_names[i]);
            if (f && lxrt_vk_calls_on) {
                lxrt_vk_real[i] = f;
                f = lxrt_vk_cnt_thunks[i];
            }
            if (f)
                __atomic_store_n(&lxrt_vk_table[i], f, __ATOMIC_RELEASE);
        }
    __atomic_store_n(&g_fill_lock, 0, __ATOMIC_RELEASE);
}

// ICD mode: 1 if `name` is a driver entry point this driver lacks, so that
// vkGetInstanceProcAddr / vkGetDeviceProcAddr answer NULL, as the Khronos
// loader would, rather than a thunk that traps at brk #2. Entry points the
// shim implements itself are not driver entry points and stay available.
__attribute__((visibility("hidden")))
int lxrt_vk_missing(const char *name)
{
    if (!lxrt_vk_icd || !name)
        return 0;
    for (unsigned i = 0; i < N_NAMES; i++)
        if (s_eq(name, k_names[i]))
            return !__atomic_load_n(&lxrt_vk_table[i], __ATOMIC_ACQUIRE);
    return 0;
}

// LXRT_VK_CALLS=1: the entry points called most since the last report, as
// "name=count" pairs in `out` (shim/scaler.c prints them with its timing).
__attribute__((visibility("hidden")))
unsigned lxrt_vk_calls_top(char *out, unsigned cap, unsigned top)
{
    static unsigned long long last[N_NAMES];
    unsigned long long d[N_NAMES];
    unsigned n = 0;
    for (unsigned i = 0; i < N_NAMES; i++) {
        unsigned long long c = lxrt_vk_counts[i];
        d[i] = c - last[i];
        last[i] = c;
    }
    for (unsigned k = 0; k < top; k++) {
        unsigned best = 0;
        for (unsigned i = 1; i < N_NAMES; i++)
            if (d[i] > d[best])
                best = i;
        if (!d[best])
            break;
        if (n && n < cap - 1)
            out[n++] = ' ';
        for (const char *p = k_names[best] + 2; *p && n < cap - 1; p++)   // without "vk"
            out[n++] = *p;
        if (n < cap - 1)
            out[n++] = '=';
        char num[24];
        unsigned m = 0;
        for (unsigned long long v = d[best]; v; v /= 10)
            num[m++] = (char)('0' + v % 10);
        while (m && n < cap - 1)
            out[n++] = num[--m];
        d[best] = 0;
    }
    out[n] = 0;
    return n;
}
""")
print(f"{len(names)} entry points -> {asm_path}, {c_path}")
